### ISSUE TITLE
Restrictive license text found in one of the versions of Coherence

### ISSUE THREAD

**Issue by rahulmohang** [oracle/coherence#113]
Hi, 

We have been trying to use the version 21.12.3 of Oracle Coherence in one of our open source projects. We downloaded the version from https://repo.maven.apache.org/maven2/com/oracle/coherence/ce/coherence/21.12.3/coherence-21.12.3-sources.jar. The sources contain the following files with a very restrictive license text:

* com/tangosol/dev/tools/copyright.cmd.txt
* com/tangosol/dev/tools/copyright.sh.txt
* com/tangosol/dev/tools/copyright.txt
* com/tangosol/dev/tools/copyright.xml.txt

The license text is the following:

@rem Oracle is a registered trademarks of Oracle Corporation and/or its
@rem affiliates.
@rem
@rem This software is the confidential and proprietary information of Oracle
@rem Corporation. You shall not disclose such confidential and proprietary
@rem information and shall use it only in accordance with the terms of the
@rem license agreement you entered into with Oracle.
@rem
@rem This notice may not be removed or altered.

This looks strange to us and the license texts seem to be there for historical reasons, and do not apply to any source file. 

Does anyone know why the files are there in that version of Coherence, and if it has any relevance or not.

**Comment by javafanboy** [comment]
As I understand it that whole folder is some remain from the Oracle product
that should have been dropped but I would let somebody actually working on
the project confirm this...

**Comment by rahulmohang** [comment]
Ok, thank you for the comment.

**Comment by thegridman** [comment]
@rahulmohang  Yes, these files are left over from the commercial Coherence version and should have been removed.

Another point, 21.12 is not a supported version. The support policy for non-LTS versions of Coherence CE is that they are only supported for six months until the next CE release comes out. The current LTS version is 22.06. The latest non-LTS version is 23.09. Using 21.12 means you could be seeing bugs, CVE's and other issues that are fixed in later versions.

**Comment by rahulmohang** [comment]
@thegridman, thank you for the comments and suggestions.

**Comment by chpatel3** [comment]
@rahulmohang Thanks for reporting the issue.

As @thegridman mentioned above, these files are left over from the commercial Coherence version and have been removed now.
