### ISSUE TITLE
Small typo in dev-guidelines and the example source code

### ISSUE THREAD

**Issue by swayamraina** [oracle/coherence#21]
There is a small error in the example and the referenced source code in `Import Declarations` section.

dev-guidelines says,
> All import statements should be sorted alphabetically.

though the example shown and the respective source file has wrong ordering

> import com.oracle.coherence.common.base.Exceptions;
> import com.oracle.coherence.common.base.Hasher;
> **import com.oracle.coherence.common.base.HashHelper;
> import com.oracle.coherence.common.base.Formatting;**
> import com.oracle.coherence.common.base.Objects;

**Comment by aseovic** [comment]
Fixed by #22
