### ISSUE TITLE
ConfigPropertyResolver.java does not permit config customization by the application in Helidon

### ISSUE THREAD

**Issue by rbair23** [oracle/coherence#35]
**Describe the bug**
My application modifies the config sources for Helidon. I found that the Coherence ConfigPropertyResolver creates its own config sources and caches it locally in the class, disregarding the config sources that are later setup by my application startup code. The problem is that Coherence cannot find the system properties that I have configured, such as the cluster name and role. 

**To Reproduce**
final var config = ... some custom config with coherence.cluster specified ...
Server.Builder serverBuilder = Server.builder().config(config);

Observe the logs, some default cluster name is used instead of what is specified in coherence.cluster

**Expected behaviour**
I should be able to define the coherence config using my own config sources and have it get used.

**Environment (please complete the following information):**
 - Coherence CE version 20.06

**Comment by thegridman** [comment]
Fixed in b257197c812610656c9b53e97db15d42b15a6cef
