### ISSUE TITLE
POF config not loaded

### ISSUE THREAD

**Issue by esestt** [oracle/coherence#36]
Version: CE 20.06.1
I created a POF config file "cache-pof-config.xml". And add below to tangosol-coherence-override.xml. When startup, it don't load cache-pof-config.xml. I also tried setting coherence.pof.config system property, didn't work.

`<serializers>
            <serializer id="java">
                <class-name>com.tangosol.io.DefaultSerializer</class-name>
            </serializer>
            <serializer id="pof">
                <class-name>com.tangosol.io.pof.ConfigurablePofContext</class-name>
                <init-params>
                    <init-param>
                        <param-type>String</param-type>
                        <param-value system-property="coherence.pof.config">cache-pof-config.xml</param-value>
                    </init-param>
                </init-params>
            </serializer>
        </serializers>`
        

In cache config file, it works by setting default serializer. 
` <defaults>
        <serializer>
            <instance>
                <class-name>com.tangosol.io.pof.ConfigurablePofContext</class-name>
                <init-params>
                    <init-param>
                        <param-type>String</param-type>
                        <param-value>cache-pof-config.xml</param-value>
                    </init-param>
                </init-params>
            </instance>
        </serializer>
    </defaults>`

**Comment by thegridman** [comment]
Just setting the config file name in the tangosol-coherence-override.xml is not enough, you need to tell Coherence to use POF as the serializer too, which you can do in two ways.
1. Set the system property `-Dcoherence.pof.enabled=true` 
2. Set it in the defaults section of your cache configuration file
```
<cache-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-cache-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-cache-config coherence-cache-config.xsd">
  <defaults>
    <serializer>pof</serializer>
  </defaults>
```

You can then set the name of the name of the configuration file to use in the override file as you did or using the `coherence.pof.config` system property, e.g. `-Dcoherence.pof.config=cache-pof-config.xml`

**Comment by esestt** [comment]
By setting coherence.pof.enabled and coherence.pof.config properties, it enable POF and load pof config correctly. But how to config serializer per cache schema. For example, I have two schemas and config as following, it behaves not as I supposed.

`
    <caching-schemes>
        <near-scheme>
            <scheme-name>schema1</scheme-name>
            <back-scheme>
                <distributed-scheme>
                    ...
                    <serializer>
                        <instance>
                            <class-name>com.tangosol.io.pof.ConfigurablePofContext</class-name>
                            <init-params>
                                <init-param>
                                    <param-type>String</param-type>
                                    <param-value>cache-pof-config.xml</param-value>
                                </init-param>
                            </init-params>
                        </instance>
                    </serializer>
                </distributed-scheme>
            </back-scheme>
        </near-scheme>
        <near-scheme>
            <scheme-name>schema2</scheme-name>
            <back-scheme>
                <distributed-scheme>
                    ...
                    <serializer id="java">
                        <class-name>com.tangosol.io.DefaultSerializer</class-name>
                    </serializer>
                </distributed-scheme>
            </back-scheme>
        </near-scheme>
    </caching-schemes>
`

**Comment by thegridman** [comment]
It is very uncommon to use a different POF configuration for different caches. Typically you just have a single configuration file that has all your POF classes in it and use it globally. 
Having said that, you can have different serialisers but it is not at the cache level it is at the Service level. Each cache maps to a `CacheService` which is what is configured in the `<caching-schemes` section. You can give each service a different serializer.
You cannot do what it appears you are trying to do in your configuration above where you try to set a different serializer for the front and back caches of a `NearCache`, this does not make sense. Why do you think you need to do this?

**Comment by esestt** [comment]
Thanks for your replies.
In my situation, I want to put java.security.PrivateKey and java.security.PublicKey objects into cache to share with all members of the cluster. These keys are implementations of java.io.Serializable.
So I want to defined two cache schemas. One use java serializer to cache Serializable objects, and the other use POF serializer to cache PortableObject objects.
If serializer config is global, how to cache keys when turn on POF?

**Comment by thegridman** [comment]
You can serialize ` java.security.PrivateKey` and `java.security.PublicKey` using POF, you just ned to configure them properly in the POF configuration file. 
You have two ways to do this:

1. If you know the implementation class that will be used for these classes then you can write a `PofSerializer` and add it to the POF configuration file just like any other POF class.

2. Alternatively  Both of those interfaces are `Serializable` and there is a POF serializer in Coherence that can serialize a Java Serializable class as POF.

Add ` java.security.PrivateKey` and `java.security.PublicKey` to your POF configuration file like this:
```
<?xml version="1.0"?>
<pof-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns="http://xmlns.oracle.com/coherence/coherence-pof-config"
              xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-pof-config coherence-pof-config.xsd">
  <user-type-list>
    <!-- by default just include coherence POF user types -->
    <include>coherence-pof-config.xml</include>

    <user-type>
      <type-id>1000</type-id>
      <class-name>java.security.PrivateKey</class-name>
      <serializer>
        <class-name>com.tangosol.io.pof.SerializableSerializer</class-name>
      </serializer>
    </user-type>

    <user-type>
      <type-id>1001</type-id>
      <class-name>java.security.PublicKey</class-name>
      <serializer>
        <class-name>com.tangosol.io.pof.SerializableSerializer</class-name>
      </serializer>
    </user-type>
  </user-type-list>

</pof-config>
```

Now you can serialize those classes, here is a simple unit tests that does it:
```
/*
 * Copyright (c) 2020 Oracle and/or its affiliates.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at
 * http://oss.oracle.com/licenses/upl.
 */
package com.oracle.coherence.example;

import com.tangosol.io.Serializer;
import com.tangosol.io.pof.ConfigurablePofContext;
import com.tangosol.util.Binary;
import com.tangosol.util.ExternalizableHelper;
import org.junit.Test;

import java.security.PrivateKey;
import java.security.PublicKey;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.MatcherAssert.assertThat;

/**
 * @author Jonathan Knight  2020.12.11
 */
public class SerializerTest
    {
    private Serializer serializer = new ConfigurablePofContext("test-pof-config.xml");

    @Test
    public void shouldSerializePrivateKey()
        {
        MyPrivateKey key = new MyPrivateKey("foo", "bar", "12345".getBytes());
        Binary binary = ExternalizableHelper.toBinary(key, serializer);
        PrivateKey result = ExternalizableHelper.fromBinary(binary, serializer);

        assertThat(result, is(notNullValue()));
        assertThat(result.getAlgorithm(), is(key.getAlgorithm()));
        assertThat(result.getFormat(), is(key.getFormat()));
        assertThat(result.getEncoded(), is(key.getEncoded()));
        }

    @Test
    public void shouldSerializePubliceKey()
        {
        MyPublicKey key = new MyPublicKey("foo", "bar", "12345".getBytes());
        Binary binary = ExternalizableHelper.toBinary(key, serializer);
        PublicKey result = ExternalizableHelper.fromBinary(binary, serializer);

        assertThat(result, is(notNullValue()));
        assertThat(result.getAlgorithm(), is(key.getAlgorithm()));
        assertThat(result.getFormat(), is(key.getFormat()));
        assertThat(result.getEncoded(), is(key.getEncoded()));
        }

    public static class MyPrivateKey
            implements PrivateKey
        {
        private final String algorithm;
        private final String format;
        private final byte[] encoded;

        public MyPrivateKey(String algorithm, String format, byte[] encoded)
            {
            this.algorithm = algorithm;
            this.format = format;
            this.encoded = encoded;
            }

        @Override
        public String getAlgorithm()
            {
            return algorithm;
            }

        @Override
        public String getFormat()
            {
            return format;
            }

        @Override
        public byte[] getEncoded()
            {
            return encoded;
            }
        }

    public static class MyPublicKey
            implements PublicKey
        {
        private final String algorithm;
        private final String format;
        private final byte[] encoded;

        public MyPublicKey(String algorithm, String format, byte[] encoded)
            {
            this.algorithm = algorithm;
            this.format = format;
            this.encoded = encoded;
            }

        @Override
        public String getAlgorithm()
            {
            return algorithm;
            }

        @Override
        public String getFormat()
            {
            return format;
            }

        @Override
        public byte[] getEncoded()
            {
            return encoded;
            }
        }
    }
```

Using Java serialization is not as efficient as POF and has other disadvantages but if you cannot write a POF serializer for a class for some reason then you can do it this way.

**Comment by esestt** [comment]
> You can serialize ` java.security.PrivateKey` and `java.security.PublicKey` using POF, you just ned to configure them properly in the POF configuration file.
> You have two ways to do this:
> 
> 1. If you know the implementation class that will be used for these classes then you can write a `PofSerializer` and add it to the POF configuration file just like any other POF class.
> 2. Alternatively  Both of those interfaces are `Serializable` and there is a POF serializer in Coherence that can serialize a Java Serializable class as POF.
> 
> Add ` java.security.PrivateKey` and `java.security.PublicKey` to your POF configuration file like this:
> 
> ```
> <?xml version="1.0"?>
> <pof-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>               xmlns="http://xmlns.oracle.com/coherence/coherence-pof-config"
>               xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-pof-config coherence-pof-config.xsd">
>   <user-type-list>
>     
>     <include>coherence-pof-config.xml</include>
> 
>     <user-type>
>       <type-id>1000</type-id>
>       <class-name>java.security.PrivateKey</class-name>
>       <serializer>
>         <class-name>com.tangosol.io.pof.SerializableSerializer</class-name>
>       </serializer>
>     </user-type>
> 
>     <user-type>
>       <type-id>1001</type-id>
>       <class-name>java.security.PublicKey</class-name>
>       <serializer>
>         <class-name>com.tangosol.io.pof.SerializableSerializer</class-name>
>       </serializer>
>     </user-type>
>   </user-type-list>
> 
> </pof-config>
> ```
> 
> Now you can serialize those classes, here is a simple unit tests that does it:
> 
> ```
> package com.oracle.coherence.example;
> 
> import com.tangosol.io.Serializer;
> import com.tangosol.io.pof.ConfigurablePofContext;
> import com.tangosol.util.Binary;
> import com.tangosol.util.ExternalizableHelper;
> import org.junit.Test;
> 
> import java.security.PrivateKey;
> import java.security.PublicKey;
> 
> import static org.hamcrest.CoreMatchers.is;
> import static org.hamcrest.CoreMatchers.notNullValue;
> import static org.hamcrest.MatcherAssert.assertThat;
> 
> /**
>  * @author Jonathan Knight  2020.12.11
>  */
> public class SerializerTest
>     {
>     private Serializer serializer = new ConfigurablePofContext("test-pof-config.xml");
> 
>     @Test
>     public void shouldSerializePrivateKey()
>         {
>         MyPrivateKey key = new MyPrivateKey("foo", "bar", "12345".getBytes());
>         Binary binary = ExternalizableHelper.toBinary(key, serializer);
>         PrivateKey result = ExternalizableHelper.fromBinary(binary, serializer);
> 
>         assertThat(result, is(notNullValue()));
>         assertThat(result.getAlgorithm(), is(key.getAlgorithm()));
>         assertThat(result.getFormat(), is(key.getFormat()));
>         assertThat(result.getEncoded(), is(key.getEncoded()));
>         }
> 
>     @Test
>     public void shouldSerializePubliceKey()
>         {
>         MyPublicKey key = new MyPublicKey("foo", "bar", "12345".getBytes());
>         Binary binary = ExternalizableHelper.toBinary(key, serializer);
>         PublicKey result = ExternalizableHelper.fromBinary(binary, serializer);
> 
>         assertThat(result, is(notNullValue()));
>         assertThat(result.getAlgorithm(), is(key.getAlgorithm()));
>         assertThat(result.getFormat(), is(key.getFormat()));
>         assertThat(result.getEncoded(), is(key.getEncoded()));
>         }
> 
>     public static class MyPrivateKey
>             implements PrivateKey
>         {
>         private final String algorithm;
>         private final String format;
>         private final byte[] encoded;
> 
>         public MyPrivateKey(String algorithm, String format, byte[] encoded)
>             {
>             this.algorithm = algorithm;
>             this.format = format;
>             this.encoded = encoded;
>             }
> 
>         @Override
>         public String getAlgorithm()
>             {
>             return algorithm;
>             }
> 
>         @Override
>         public String getFormat()
>             {
>             return format;
>             }
> 
>         @Override
>         public byte[] getEncoded()
>             {
>             return encoded;
>             }
>         }
> 
>     public static class MyPublicKey
>             implements PublicKey
>         {
>         private final String algorithm;
>         private final String format;
>         private final byte[] encoded;
> 
>         public MyPublicKey(String algorithm, String format, byte[] encoded)
>             {
>             this.algorithm = algorithm;
>             this.format = format;
>             this.encoded = encoded;
>             }
> 
>         @Override
>         public String getAlgorithm()
>             {
>             return algorithm;
>             }
> 
>         @Override
>         public String getFormat()
>             {
>             return format;
>             }
> 
>         @Override
>         public byte[] getEncoded()
>             {
>             return encoded;
>             }
>         }
>     }
> ```
> 
> Using Java serialization is not as efficient as POF and has other disadvantages but if you cannot write a POF serializer for a class for some reason then you can do it this way.

Thank you very much!
