### ISSUE TITLE
Cache frequently used data from Informix db

### ISSUE THREAD

**Issue by jacob2221** [oracle/coherence#37]
Hi,

We are using weblogic 12.2.1.4 app server to host our java apps. Also using Informix 14 as database. Would it be possible to coherence community edition in this landscape to cache frequently queried data from db to improve performance?

Regards
Jacob

**Comment by aseovic** [comment]
Sure. Coherence doesn't really care which app server you are using in front of it, or which database (if any) you are using behind it.

We do have some features in the commercial editions that provide tighter integration with WLS in particular, but if you don't care about those Community Edition can certainly be used as a general-purpose distributed caching solution for your Java EE apps running on WebLogic, or any other app server.

**Comment by harveyraja** [comment]
@jacob2221 Coherence commercial edition is bundled with WLS and if you have WLS Suite then you have Coherence commercial edition as a part of that suite.

If you do *not* have WLS Suite and want to use Coherence Community Edition, you will need to use a Filtering class loader to ensure the classes from the community edition jar are loaded from the application and not from the classes in the commercial edition on the WLS class path. Its fairly simple change to the weblogic-application.xml file:
```
<prefer-application-packages>
  <package-name>com.tangosol.*</package-name>
  <package-name>com.oracle.coherence.*</package-name>
</prefer-application-packages>
```

You will need to ensure that you provide all the relevant information for Coherence to create the relevant cluster; cluster name, WKA, etc.

**Comment by jacob2221** [comment]
Thanks @aseovic and @harveyraja for your inputs. I came across this link https://docs.oracle.com/middleware/1212/coherence/COHTU/cohjdev.htm#BABHCGAF (Section 9.3) - "Creating a Database Cache". Is this the best way to implement a database cache using coherence community edition via JDBC? The example uses a single table. Is there any other documentation/examples which will give more details on how to implement this for an application where we may want to cache multiple tables with dependencies b/w them. Also will coherence internally take care of ensuring that any changes to cache go to DB and vice versa?

**Comment by harveyraja** [comment]
@jacob2221 take a look at the following links:

1. A [description of CacheStore](https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/develop-applications/caching-data-sources.html#GUID-9FAD1BFB-5063-4995-B0A7-3C6F9C64F600) which is a generic means of integrating cache contents with *any* data source.
2. [Using JPA](https://docs.oracle.com/en/middleware/standalone/coherence/14.1.1.0/integrate/using-jpa-coherence.html#GUID-E96BE88C-1771-4552-BAF6-25E4EF9B8B5C) as means of translating between relational form to object form, as the latter is stored in the cache.

By your comment of using Coherence CE to integrate with JDBC and your desire to sync multiple tables with relationships, I think you want some form of JPA integration such as hibernate. [Here](https://github.com/coherence-community/coherence-hibernate) is a link to our hibernate integration project for more info. Any issues / questions are prob best served in that repo.

**Comment by harveyraja** [comment]
BTW - if you have enough info and agree please close this issue.

**Comment by jacob2221** [comment]
Thanks @harveyraja for the details
