### ISSUE TITLE
Does Coherence work on ARM architecture?

### ISSUE THREAD

**Issue by javafanboy** [oracle/coherence#54]
## Type of question

Coherence CPU architecture support

## Question
Does Coherence work on ARM architecture (like the AWS Graviton2) or only with X86?

**Comment by aseovic** [comment]
Coherence is pure Java, so it works on anything Java works on, including ARM.

That said, we did notice some issues in our nightly ARM builds with Java 8, but Java 11 ARM builds work fine, so I'd strongly suggest using Java 11 or later.
