### ISSUE TITLE
Coherence CE transaction support?

### ISSUE THREAD

**Issue by javafanboy** [oracle/coherence#66]
I need some general guidance on what support is available in Coherence CE for transactional update of multiple objects at the same time (in addition to what can be done with entry processors).  

At one hand the documentation states that "Transaction Framework" is not included in CE on the other hand I can see that the CacheAdapter class is present in the source code? 

Is the intention that you need to write your own equivalent of the old coherence-tx.rar (that is not provided with CE) or what is the intended use of CacheAdpater?

**Comment by thegridman** [comment]
As you have seen, transaction support is a commercial feature and not in CE. From looking at the code I would think the `CacheAdapter` class is in CE by mistake.

Personally, way back when I was a Coherence customer, I thought the transaction API was too restrictive. The majority of applications I was involved with required the use of cache features that were not allowed on a transactional cache.

**Comment by javafanboy** [comment]
Thanks for clarifying that and yes I am looking into an algorithm based on
entry processors instead - just wanted to know what features that where
available and not "for the record"....
