### ISSUE TITLE
Relationship between future releases of Coherence Enterprise/Grid and Coherence Community

### ISSUE THREAD

**Issue by RobertoMalatesta** [oracle/coherence#81]
First and foremost a big thank you to Oracle for open-sourcing this great product.

I have a couple of questions for the Oraclers here around:

1 - What will be the future relationship between Community and Coherence Enterprise/Grid in terms of source code? 
Will CE be the base for future releases of the commercial product as well?

2 - Version numbering: will at some point Coherence Grid and Enterprise adopt the same version numbering of CE?

TY,

R

**Comment by aseovic** [comment]
For general questions like this one, it is probably better to use [discussions](https://github.com/oracle/coherence/discussions), but let me reply to first question:

The CE source code is always in sync with commercial product, but CE is released more frequently, so some of the new features may only available in CE until the next LTS release that brings them back in sync. For example, we released Coherence CE 22.06 LTS in June, and then commercial 14.1.1.2206 feature pack for 14.1.1.x release in July that have identical features. That allows us to incubate new features over several CE releases, before making them available in a CE LTS and commercial release.
 
@rstafford Can you please respond to the second question?

**Comment by aseovic** [comment]
Actually, I can probably respond to the versioning question as well.

Ideally, we'd like to get to the point where both the version number and the release schedule are the same for both community and commercial editions, but unfortunately we are not there yet, for a variety of reasons that are mostly out of our control.

So hopefully, yes, they should follow the same versioning scheme at some point, but it is hard to say when that may happen.

**Comment by RobertoMalatesta** [comment]
Thank you @aseovic for the detailed answers.
On versions: yes, we will see. Having two different version numberings would not be a great problem since we will have a correspondence btw CE milestones and commercial releases.

R
