### ISSUE TITLE
COH-23644?

### ISSUE THREAD

**Issue by javafanboy** [oracle/coherence#95]
I am working in a project where we due to limitations of using JDK 8 and other components used are "stuck" with Coherence CE 14 and is having a challenge where evicting entries in the local cache (part of a near cache) takes a LONG time. 

I realize this is not a supported release so we are looking into solving the problem ourselves but have a specific question that could help us in this...

We are profiling and seeing that the line that seem to take a lot of time is " iterEvict.remove()" in OldCache and is marked with an issue "COH-23644" that we assume introduced the line.

Not sure if this is a reference to an issue in Coherence CE or an internal Oracle issue to the enterprise edition but either way we have not been able to find any info about it and are very curious to what the issue was and why the line was introduced...

Naively when looking at the code it seems to remove keys from an ArrayList of elements to be evicted as it is iterated - it is not clear to us WHY there is a need to do this and in general removing elements from ArrayLists is expensive (at least in the past required copying the array) so we are suspecting this could be at least one reason we see slow eviction (our caches are big and so could the list of keys to evict be)....

Our first work-around that we are testing now is to increase the low-units to be about 99% of the high-units to ensure the size of the array list will be small (then the ~O(n ** 2) effect of the repeated array.remove operation is minimized) - lets see if it works...

We are also considering, as a further work around, try using Caffeine (2.X version ) as a local cache with this Coherence CE release (using the old lower level mechanism that has been available to provide your owen cache implementation) but not sure how well it would work - are experiences of this would be welcome!

I have noticed that the above mentioned line is present also in the latest Coherence CE release so if this is the cause of the problem we are seeing it may be present also with the latest...

**Comment by javafanboy** [comment]
Can report that the work around to increase the low-units to be very close to high-units (this way ensuring that a small number of entries are evicted each time a "prune" is performed seem to have improved the situation but now we instead have very frequent prunes which is not ideal either... 

Woulds appreciate info about IF that line that remove the entries from the list as they are processed is really needed (I would naively assume the whole prune operation is executed inside a "synchronized" block preventing any other operations on the local cache and in that case I do not immediately see the need to remove the elements instead of just letting them be and afterwards empty the whole array at once if it is retained ror just discard it if it is temporary) and if so if you have some other suggestions of improvements to the code we can add in a "patch" for our own use... maybe use a double linked list instead of an array list that have a O(1) complexity for deleting an entry?!

**Comment by mgamanho** [comment]
Hi @javafanboy 

So far as I can tell, this is a memory use improvement to address instances of OOM that we saw. It's just to release references early, and I believe should be safe for you to just undo that line. Said references will be released eventually.

If memory usage is not a concern for you, I would say just go ahead and "patch".

We'll investigate this on our side. Thanks for finding it.

**Comment by javafanboy** [comment]
I have never tried building Coherence before and when following the instructions it eventually reported build complete but nothing shows up under the /dist directory?! Any ideas what is up?

I have for instance tried "mvn -am -pl coherence clean install -DskipTests -Dtde.compile.not.required" that reports the build as successful but leaves dist empty (only original readme file is there)?

A quick search for "coherence*.jar" results in:
/prj/coherence-core-components/target/coherence-core-components-14.1.1-0-13-SNAPSHOT-sources.jar
./prj/coherence-core-components/target/coherence-core-components-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-core/target/coherence-core-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-core/target/coherence-core-14.1.1-0-13-SNAPSHOT-tests.jar
./prj/coherence-core/target/coherence-core-14.1.1-0-13-SNAPSHOT-sources.jar
./prj/coherence-discovery/target/coherence-discovery-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-docker/target/coherence-docker-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-http-netty/target/coherence-http-netty-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-javadoc/target/coherence-javadoc-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-jcache/target/coherence-jcache-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-loadbalancer/target/coherence-loadbalancer-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-login/target/coherence-login-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-management/target/coherence-management-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-metrics/target/coherence-metrics-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-mock/target/coherence-mock-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-rest/target/coherence-rest-14.1.1-0-13-SNAPSHOT-tests.jar
./prj/coherence-rest/target/coherence-rest-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence-testing-support/target/coherence-testing-support-14.1.1-0-13-SNAPSHOT.jar
./prj/coherence/target/coherence-14.1.1-0-13-SNAPSHOT.jar
./prj/test/performance/framework/target/lib/14.1.1-0/coherence.jar
./prj/test/performance/framework/target/coherence-performance-framework-14.1.1-0-13-SNAPSHOT.jar
./prj/test/performance/psr/target/lib/14.1.1-0/coherence.jar
./prj/test/performance/psr/target/coherence-performance-psr-14.1.1-0-13-SNAPSHOT.jar
./prj/test/performance/target/lib/14.1.1-0/coherence.jar
./tde/core-net/3.0/target/coherence.jar
./tde/core/1.3/ext/coherence-core.jar
./tde/core/1.3/ext/coherence-discovery.jar
./tools/tde/lib/coherence.jar

Also in the v14.1.1 I downloaded there is a readme.txt (in addition to the README.md) that seem to contain some old / misleading instructions (Oracle internal for the Enterprise edition?) that had me confused at first...

**Comment by mgamanho** [comment]
When you build like that (mvn ... install), the jar ends up in the maven repository, usually in ~/.m2/repository/com/oracle/...

Otherwise the main jar can also be found in ./prj/coherence/target/coherence-14.1.1-0-13-SNAPSHOT.jar it's the same file. Useful for debugging or prototyping purposes.

I wouldn't worry about making any mistakes running these config files, Coherence doesn't depend on any "hidden" magic ala Windows registry :)
I'll look into those, at any rate.

**Comment by javafanboy** [comment]
Thanks for the info and happy to hear there are no similarities between
Coherence and with Windows :-)

**Comment by javafanboy** [comment]
As the devs in my project mostly use Windows Laptops I can report that I also tried building 14.1.1.0 under Windows but right away the testApproximateDurationToString (DuratiionTest.java) failed with the message below (I have not tried to figure out why). I used Maven 3.9.0 OpenJDK 1.8, Windows 10.

DurationTest.testApproximateDurationToString:110 expected:<1[.]50ms> but was:<1[,]50ms>

**Comment by thegridman** [comment]
Off the top of my head, I wonder if the `DuratiionTest.java` failure is a region thing. I notice in your error message it says, `expected:<1[.]50ms> but was:<1[,]50ms>`, i.e the test expects a decimal point (as this is hard coded in the test code), but your region settings use a comma in place of a decimal point (like we do here in Turkey, although my laptop uses English for it region settings). We run all our CI builds on a number of different OS'es including versions of Windows and they all pass but they are all on US based Jenkins slaves. I'm sure we do not run builds with non-English regions, maybe we should try one and see what happens.

**Comment by javafanboy** [comment]
The "patch" of removing the line worked - we no longer see minute long delays in eviction where one core run  at 100%. No negative effects observed in our testing.
