### ISSUE TITLE
Is "-Dtangosol.coherence.override" not used in Coherence CE? Still talking about the old v14 sorry for that.... :-(

### ISSUE THREAD

**Issue by javafanboy** [oracle/coherence#97]
According to the documentation shared between Oracle Coherence and Coherence CE one should be able to specify an "override file" with -Dtangosol.coherence.override but as far as we can tell (we just noticed it and is still investigating/finding work arounds), at least in V14 that we still use, this parameter is ignored by CE and only the file "jar:file:/opt/oas/cache/lib/cache-coherence-2.7941.0.jar!/tangosol-coherence-override-prod.xml" seem to be read?!
Not sure if this is the intended behaviour in CE and if so is it documented somewhere?

**Comment by mgamanho** [comment]
We're phasing out the 'tangosol.' part from configs. Try using 'coherence.override' and see if it helps. If not let us know we'll investigate.
I'll verify and check whether we document this.

**Comment by chpatel3** [comment]
Hi @javafanboy, we need couple of clarification

1) What do you set -Dtangosol.coherence.override to?
2) What is the content of the "jar:file:/opt/oas/cache/lib/cache-coherence-2.7941.0.jar!/tangosol-coherence-override-prod.xml" which is packaged inside your cache-coherence-2.7941.0.jar?

**Comment by javafanboy** [comment]
1. We set it to the name of a file that is located in the root of the same JAR file as and side by side with the tangosol-coherence-override-prod.xml (that is loaded instead). We have a large number of different override files there for different configurations that we need to select based on environment using the "-Dtangosol.coherence.override" property but as mentioned for some reason we don't manage to get working...
2. That is a "default" config that we use if no override is specified but we plan to always use one of the override files for real environments so it is just a fall back for test on a laptop or something...

I also have a question about a parameter called "-Dcoherence.mode" - is this used for Coherence CE or is it just a licensing thing for the enterprise edition? If it is used what exactly does it do in CE - the description in the doc is not very "compete"...

**Comment by thegridman** [comment]
Maybe we should explain how the Operational config is loaded.

1. Coherence loads it's root Operational config from `coherence.jar` - this is the `tangosol-coherence.xml` file and you should never replace this with a file of the same name.
2. In the root `<coherence>` element of the `tangosol-coherence.xml` file is this attribute `xml-override="/tangosol-coherence-override-{mode}.xml"` which specifies that the overrides to apply should come from a file named `tangosol-coherence-override-{mode}.xml` where `{mode}` get replaced with the value from the `coherence.mode` System property. Coherence includes a `tangosol-coherence-override-dev.xml` `tangosol-coherence-override-prod.xml` and `tangosol-coherence-override-eval.xml` files in `coherence.jar`
3. The root `<coherence>` element of the `tangosol-coherence-override-{mode}.xml`  files contains `xml-override="{coherence.override /tangosol-coherence-override.xml}"` which means after loading the correct `tangosol-coherence-override-{mode}.xml` file, more overrides will be applied by loading the `tangosol-coherence-override.xml` file (or whichever file is specified by the `coherence.override` System property.

So the question asked by Chinmay above should maybe have been clearer - is the file `tangosol-coherence-override-prod.xml` in your `cache-coherence-2.7941.0.jar` a custom override file you have written yourself, and not a copy of the `tangosol-coherence-override-prod.xml` file from `coherence.jar`? If it is your own xml file, and it does not have the `xml-override="{coherence.override /tangosol-coherence-override.xml}"` attribute in the root `<coherence>` element, then whatever is specified by `-Dcoherence.override` will not be loaded.

Regarding the `coherence.mode` property; many versions ago Coherence used to recommend some slightly different configurations between environments like Dev and Prod, and the method of loading overrides allowed for this. In more recent versions, the need for these differences have gradually been removed until now I believe the only difference is the log buffer limit.

**Comment by javafanboy** [comment]
Thanks for the full explanation - I can now confirm that we with a minimal example (using the DefaultCacheServer) managed to get the override file to load so this is NOT an error in Coherence CE as we first speculated.

But are still struggling with our real environment deploy where we neither see any log saying that the override is read or ignored/not-found etc but do see the following warning and error messages where we would have EXPECTED to see this type of log entries (i.,e. where other logging is emitted about loaded and not provided override files):

**To guard against XXE vulnerabilities, ensure provided XML parser is secure.
Validator: org.apache.xerces.jaxp.validation.ValidatorImpl
Error: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.**

Right now we are working with the theory that loading the override somehow triggers this error resulting in ity being ignored.  Unfortunately we do not have any "XML Guru" in our team so we are a little bit unsure how to proceed debugging the error...
The search goes on - we are suspicious if we in some way has specified an XML parser version in the classpath (that is like a mile long as we also use wildfly and a lot of other stuff) that causes the problem (i.e. we suffers from some "JAR hell" thing) but that is more of a guess than built on any facts right now...

The override file we TRY to load is syntactically correct and looks like this:

<?xml version='1.0'?>

<coherence  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://xmlns.oracle.com/coherence/coherence-operational-config"
        xsi:schemaLocation="http://xmlns.oracle.com/coherence/coherence-operational-config coherence-operational-config.xsd"
        xml-override="/tangosol-coherence-override.xml">
	<cluster-config>
		<unicast-listener>
			<well-known-addresses>
			  <socket-address id="1">
				<address system-property="tangosol.coherence.wka">l4091p</address>
				<port system-property="tangosol.coherence.wka.port">9000</port>
			  </socket-address>
			  <socket-address id="2">
				<address system-property="tangosol.coherence.wka2">l4092p</address>
				<port system-property="tangosol.coherence.wka2.port">9000</port>
			  </socket-address>
			  <socket-address id="3">
				<address system-property="tangosol.coherence.wka3">l4093p</address>
				<port system-property="tangosol.coherence.wka3.port">9000</port>
			  </socket-address>
			  <socket-address id="4">
				<address system-property="tangosol.coherence.wka4">l4094p</address>
				<port system-property="tangosol.coherence.wka4.port">9000</port>
			  </socket-address>			  
		  </well-known-addresses>
		</unicast-listener> 
		<authorized-hosts>
		 
          <host-range>
             <from-address>138.106.96.151</from-address>
              <to-address>138.106.96.194</to-address>
          </host-range>
        </authorized-hosts>
	</cluster-config>
    <logging-config>
        <destination system-property="tangosol.coherence.log">log4j</destination>
        <severity-level system-property="tangosol.coherence.log.level">3</severity-level>
    </logging-config>
    <management-config>
        <refresh-expiry system-property="tangosol.coherence.management.refresh.expiry">10s</refresh-expiry>
        <read-only system-property="tangosol.coherence.management.readonly">false</read-only>
    </management-config>
</coherence>

**Comment by thegridman** [comment]
The message "To guard against XXE vulnerabilities..." is a warning because you have Xerces on your class path and version of Xerces being used does not support JAXP version 1.5. The just means you have no protection against XXE and can be ignored, it is not the cause of any issues loading the overrides files.

Coherence logs out the Operational configurations it is loading when it starts, for example:
```
2023-03-08 20:20:59.936/0.449 Oracle Coherence 15.1.1.0.0 (dev-jonathanknight) <Info> (thread=Coherence, member=n/a): Loaded operational configuration from "jar:file:/Users/jonathanknight/dev/Coherence/dev/main/prj/coherence/target/coherence-15.1.1-0-0-SNAPSHOT.jar!/tangosol-coherence.xml"
2023-03-08 20:21:00.006/0.506 Oracle Coherence 15.1.1.0.0 (dev-jonathanknight) <Info> (thread=Coherence, member=n/a): Loaded operational overrides from "jar:file:/Users/jonathanknight/dev/Coherence/dev/main/prj/coherence/target/coherence-15.1.1-0-0-SNAPSHOT.jar!/com/oracle/coherence/defaults/tangosol-coherence-override-dev.xml"
2023-03-08 20:21:00.008/0.507 Oracle Coherence 15.1.1.0.0 (dev-jonathanknight) <Info> (thread=Coherence, member=n/a): Optional configuration override "/tangosol-coherence-override.xml" is not specified
```

The log above shows Coherence first loads `coherence-15.1.1-0-0-SNAPSHOT.jar!/tangosol-coherence.xml`, then it loads `tangosol-coherence-override-dev.xml` and finally it says there is no `/tangosol-coherence-override.xml` file on the class path.

If I specify `-Dcoherence.override=foo.xml` where `foo.xml` does not exist, then it los this:
```
2023-03-08 20:21:53.920/0.450 Oracle Coherence 15.1.1.0.0 (dev-jonathanknight) <Info> (thread=Coherence, member=n/a): Loaded operational configuration from "jar:file:/Users/jonathanknight/dev/Coherence/dev/main/prj/coherence/target/coherence-15.1.1-0-0-SNAPSHOT.jar!/tangosol-coherence.xml"
2023-03-08 20:21:53.990/0.507 Oracle Coherence 15.1.1.0.0 (dev-jonathanknight) <Info> (thread=Coherence, member=n/a): Loaded operational overrides from "jar:file:/Users/jonathanknight/dev/Coherence/dev/main/prj/coherence/target/coherence-15.1.1-0-0-SNAPSHOT.jar!/com/oracle/coherence/defaults/tangosol-coherence-override-dev.xml"
2023-03-08 20:21:53.992/0.509 Oracle Coherence 15.1.1.0.0 (dev-jonathanknight) <Info> (thread=Coherence, member=n/a): Optional configuration override "foo.xml" is not specified
```

Where the final line says `"foo.xml" is not specified` so it is ignored and Coherence continues to start.

So the log should be displaying exactly what Coherence is loading (or not able to find).

**Comment by javafanboy** [comment]
Thanks for all the information and helpful advice - we found no less than 3 errors in our configuration that together gave the problem we observed that we now have managed to fix - the way config files work in Coherence is powerful but a bit complex...
